name: Client CI/CD

on:
  push:
    branches:
      - "main"
    paths:
      - "client/**"
      - "common/**"

  pull_request:
    branches:
      - "main"
    paths:
      - "server/**"
      - "common/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.20.0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        run: pnpm --filter tachi-client... --filter . install

      - name: Lint
        run: pnpm --filter tachi-client lint

      - name: Typecheck
        run: pnpm --filter tachi-client typecheck

  deploy:
    runs-on: [ubuntu-latest]
    needs: test
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.20.0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Enable SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

      - name: Install dependencies
        run: pnpm --filter tachi-client... --filter . install

      - name: Build Bokutachi
        run: pnpm --filter tachi-client build
        env:
          VITE_GIT_REPO: "GitHub:zkldi/Tachi"
          VITE_TCHIC_MODE: "boku"
          VITE_GOATCOUNTER: "https://tachi.goatcounter.com/count"
          VITE_RECAPTCHA_KEY: "6LdRRKopAAAAAGNmmGSmUvkD64nysrFgSSWLq9LL"
          VITE_SERVER_URL: "https://boku.tachi.ac"
          VITE_DISCORD: "https://discord.gg/E4n8ZZF5ES"
          VITE_CDN_URL: "https://cdn-boku.tachi.ac"
          TACHI_NAME: "Bokutachi"
          BUILD_OUT_DIR: "~/boku"

      - name: Build Kamaitachi
        run: pnpm --filter tachi-client build
        env:
          VITE_GOATCOUNTER: "https://tachi.goatcounter.com/count"
          VITE_SERVER_URL: "https://kamai.tachi.ac"
          VITE_EAG_CLIENT_ID: "C341A6CA3E72D48F0B20E84C045D15BFACD88E0A"
          VITE_FLO_CLIENT_ID: "F0C0F66355B954F5DB5472AE21C59295403D60CC"
          VITE_DISCORD: "https://discord.gg/NNgGJbpQUj"
          VITE_TCHIC_MODE: "kamai"
          VITE_CDN_URL: "https://cdn-kamai.tachi.ac"
          VITE_GIT_REPO: "GitHub:zkldi/Tachi"
          VITE_RECAPTCHA_KEY: "6LdRRKopAAAAAGNmmGSmUvkD64nysrFgSSWLq9LL"
          TACHI_NAME: "Kamaitachi"
          BUILD_OUT_DIR: ~/kamai

      - name: Deploy Kamaitachi
        run: scp -r ~/kamai ci@"$TACHI_HOST":tachi-client
        env:
          TACHI_HOST: ${{secrets.TACHI_HOST}}

      - name: Deploy Bokutachi
        run: scp -r ~/boku ci@"$TACHI_HOST":tachi-client
        env:
          TACHI_HOST: ${{secrets.TACHI_HOST}}
